from setuptools import setup, find_packages

setup(
    name="nlmap-qwen3",
    version="1.0.0",
    author="Xiao Yujie",
    author_email="12433332@mail.sustech.edu.cn",
    description="NLMap + Qwen3 Robot Navigation System",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/xiaoyu0426/robot-navigation-nlmap-qwen3",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.5.0",
        "transformers>=4.52.0",
        "numpy>=2.1.0",
        "opencv-python>=4.11.0",
        "Pillow>=11.0.0",
        "scipy>=1.15.0",
        "scikit-learn>=1.6.0",
        "tensorflow>=2.19.0",
        "open3d>=0.19.0",
        "matplotlib>=3.10.0",
        "pandas>=2.2.0",
        "huggingface-hub>=0.32.0",
        "safetensors>=0.5.0",
        "accelerate>=1.7.0",
        "tqdm>=4.67.0",
        "requests>=2.32.0",
        "PyYAML>=6.0.0",
        "streamlit>=1.45.0",
    ],
)
